source 'http://rubygems.org'
gem 'haml', '4.0.5'
gem 'savon', '2.3.2'
gem 'sinatra', '1.4.4'
gem 'sinatra-static-assets', '1.0.3'
gem 'sinatra-contrib', '1.4.2'
gem 'shotgun', '0.9'
gem 'encryptor', '1.3.0'
gem 'pony', '1.6.2'
gem 'tassadar'