source 'http://rubygems.org'
gem 'haml' 
gem 'sinatra'
gem 'sinatra-static-assets'
gem 'sinatra-contrib'
gem 'bzip2-ruby', git: 'https://github.com/chewi/bzip2-ruby'
gem 'shotgun'
gem 'encryptor'
gem 'tassadar'
gem 'datamapper'
gem 'dm-sqlite-adapter'
gem 'mpq'
gem 'sc2-rep-parser', git: 'https://github.com/horizonshadow/sc2-rep-parser.git'
gem 'pry'
gem 'puma'
gem 'rack'
