source 'http://rubygems.org'
gem 'haml' 
gem 'sinatra'
gem 'sinatra-static-assets'
gem 'sinatra-contrib'
gem 'shotgun'
gem 'encryptor'
gem 'datamapper'
gem 'dm-sqlite-adapter'
gem 'pry'
gem 'thin'
gem 'rack'
gem 'sc2replaystats', git: 'https://github.com/HorizonShadow/ruby-sc2replaystats.git'
gem 'sinatra-websocket'
gem 'eventmachine', '1.0.9.1', platforms: :ruby
